version: '3.8' 
services:
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./testdata:/home/testdata
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
  
  datanode1:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode1
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    expose:
      - 50075
    ports:
      - 50075:50075

  datanode2:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    container_name: datanode2
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    expose:
      - 50076
    ports:
      - 50076:50075

  # datanode3:
  #   image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
  #   container_name: datanode3
  #   depends_on: 
  #     - namenode
  #   volumes:
  #     - ./data/datanode3:/hadoop/dfs/data
  #   env_file:
  #     - ./hadoop.env
  #   ports:
  #     - 50077:50075

  # spark-master:
  #   image: bde2020/spark-master:2.1.0-hadoop2.8-hive-java8
  #   container_name: spark-master
  #   expose:
  #     - 8080
  #   ports:
  #     - 8080:8080
  #     - 7077:7077
  #   env_file:
  #     - ./hadoop.env
  
  # spark-worker:
  #   image: bde2020/spark-worker:2.1.0-hadoop2.8-hive-java8
  #   depends_on:
  #     - spark-master
  #   environment:
  #     - SPARK_MASTER=spark://spark-master:7077
  #   ports:
  #     - 8081:8081
  #     - 8889:8889
  #   env_file:
  #     - ./hadoop.env
      
  # spark-notebook:
  #   image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
  #   container_name: spark-notebook
  #   env_file:
  #     - ./hadoop.env
  #   ports:
  #     - 9001:9001
